# Generated by Django 3.0.8 on 2020-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200731_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter a book language (e.g. English, Japan, Germany)', max_length=200, verbose_name='Language'),
        ),
    ]
